title: Zhongzheng Li's Homepage
page-top-title: Zhongzheng Li
top-section-bg-text: Computer Science
home-subtitle: Zhongzheng Li&ensp;|&ensp;李中政
copyright-text: '&copy; Zhongzheng Li 2023-2024. All Rights Reserved.'
